### ISSUE TITLE
missing paramter in constructor

### ISSUE THREAD

**Issue by bigerl** [dice-group/Ontolearn#103]
`F1()` in `quality_func=F1()` is missing a mandatory argument `learning_problem`: 
https://github.com/dice-group/OntoPy/blob/ee5428b91624f960efeecd1313695034fe5e7a78/ontolearn/rl.py#L29-L43

see:

https://github.com/dice-group/OntoPy/blob/ee5428b91624f960efeecd1313695034fe5e7a78/ontolearn/metrics.py#L85-L94

**Comment by SimonBin** [comment]
should be fixed now. can you verify?
