### ISSUE TITLE
Test the endpoint

### ISSUE THREAD

**Issue by SimonBin** [dice-group/Ontolearn#155]
If possible an automated test for the [endpoint](https://github.com/dice-group/Ontolearn/blob/e0d692bdc5d30f96367c0089d2d28e93423a7902/ontolearn/endpoint/simple_drill_endpoint) should be devised

**Comment by Demirrr** [comment]
Please also add a test for the hobbit endpoint as well. If the hobbit endpoint is not reachable,  the action of "Verify external files" fails with the following output:

```
Verifying embeddings.zip...
Verify failed, file not found
Verifying KGs/Carcinogenesis/carcinogenesis.owl...
Verify failed, file not found
Verifying KGs/dbpedia_2016-10.owl...
Verify failed, file not found
Verifying KGs/Mutagenesis/mutagenesis.owl...
Verify failed, file not found
Verifying KGs/Nctrer/nctrer.owl...
Verify failed, file not found
Verifying KGs.zip...
Verify failed, file not found
Verifying pre_trained_agents.zip...
Verify failed, file not found
Errors.
```
I reckon it would be very helpful to indicate the user that this fail can also be caused by the endpoint
