### ISSUE TITLE
Some flake8 errors in Drill

### ISSUE THREAD

**Issue by SimonBin** [dice-group/Ontolearn#159]
./ontolearn/concept_learner.py:469:19: F821 undefined name 'string_balanced_pos'
./ontolearn/concept_learner.py:595:19: F821 undefined name 'string_balanced_pos'
./ontolearn/concept_learner.py:877:16: F821 undefined name 'node'
./ontolearn/concept_learner.py:878:28: F821 undefined name 'get_full_iri'
./ontolearn/concept_learner.py:878:71: F821 undefined name 'node'
./ontolearn/concept_learner.py:887:17: F821 undefined name 'node'
./ontolearn/concept_learner.py:891:28: F821 undefined name 'node'
./ontolearn/concept_learner.py:893:27: F821 undefined name 'node'
./ontolearn/concept_learner.py:895:27: F821 undefined name 'node'

**Comment by Demirrr** [comment]
The part starting from from 876 to 900 are commented as this part is related to a possible extendion of representing an RL state based on sampling individuals. We do not work on this idea yet.
