### ISSUE TITLE
Increase code coverage

### ISSUE THREAD

**Issue by SimonBin** [dice-group/Ontolearn#160]
This is a general tracking issue which suggests to use `pytest --cov` or similar plus manual evaluation of the XML reports (eg. in PyCharm) to increase our test coverage

**Comment by alkidbaci** [comment]
---------- coverage: platform win32, python 3.9.12-final-0 -----------
Name                                                            Stmts   Miss  Cover
------------------------------------------------------------------------
ontolearn\__init__.py                                           2      0   100%
ontolearn\abstracts.py                                    283    129    54%
ontolearn\base_concept_learner.py                208     16    92%
ontolearn\base_nces.py                                    77     60    22%
ontolearn\concept_generator.py                      88      0   100%
ontolearn\concept_learner.py                       1042    577    45%
ontolearn\core\__init__.py                                   0      0   100%
ontolearn\core\owl\__init__.py                            0      0   100%
ontolearn\core\owl\hierarchy.py                     248     60    76%
ontolearn\core\owl\utils.py                             430     88    80%
ontolearn\data_struct.py                                 154    122    21%
ontolearn\ea_algorithms.py                            152     74    51%
ontolearn\ea_initialization.py                          226     13    94%
ontolearn\ea_utils.py                                         86      5    94%
ontolearn\fitness_functions.py                          13      0   100%
ontolearn\heuristics.py                                      91     47    48%
ontolearn\knowledge_base.py                        363     40    89%
ontolearn\learning_problem.py                        33      2    94%
ontolearn\learning_problem_generator.py     241     79    67%
ontolearn\metrics.py                                         50     16    68%
ontolearn\model_adapter.py                           147     39    73%
ontolearn\nces_architectures.py                       72     62    14%
ontolearn\nces_modules.py                              53     37    30%
ontolearn\nces_trainer.py                               174    151    13%
ontolearn\nces_utils.py                                     24     13    46%
ontolearn\owlapy\__init__.py                              0      0   100%
ontolearn\owlapy\_utils.py                                 7      0   100%
ontolearn\owlapy\ext\__init__.py                      32      4    88%
ontolearn\owlapy\fast_instance_checker.py   392     90    77%
ontolearn\owlapy\io.py                                    13      3    77%
ontolearn\owlapy\model\__init__.py             1665    344    79%
ontolearn\owlapy\model\_base.py                   33     10    70%
ontolearn\owlapy\model\_iri.py                        83      6    93%
ontolearn\owlapy\model\providers.py              37      3    92%
ontolearn\owlapy\namespaces.py                     29      4    86%
ontolearn\owlapy\owl2sparql\__init__.py             0      0   100%
ontolearn\owlapy\owl2sparql\converter.py     367    130    65%
ontolearn\owlapy\owlready2\__init__.py             4      0   100%
ontolearn\owlapy\owlready2\_base.py             548     94    83%
ontolearn\owlapy\owlready2\axioms.py           502    130    74%
ontolearn\owlapy\owlready2\complex_ce_instances.py      64     21    67%
ontolearn\owlapy\owlready2\utils.py                265     21    92%
ontolearn\owlapy\parser.py                               365     17    95%
ontolearn\owlapy\render.py                              241     14    94%
ontolearn\owlapy\util.py                                    336     22    93%
ontolearn\owlapy\vocab.py                                 90      3    97%
ontolearn\refinement_operators.py                   580    111    81%
ontolearn\search.py                                           449    155    65%
ontolearn\utils\__init__.py                                  124     89    28%
ontolearn\utils\log_config.py                              30     10    67%
ontolearn\utils\oplogging.py                                8      0   100%
tests\test_owlapy_cnf_dnf.py                               69      0   100%
tests\test_owlapy_fastinstancechecker.py          246      1    99%
tests\test_owlapy_nnf.py                                    246      0   100%
tests\test_owlapy_owl2sparql_converter.py       197      5    97%
tests\test_owlapy_owlready2.py                         585      1    99%
tests\test_owlapy_parser.py                                345      0   100%
tests\test_owlapy_render.py                               132      1    99%
tests\test_refinement_operators.py                    205      1    99%
tests\test_value_splitter.py                                   47      1    98%
------------------------------------------------------------------------
TOTAL                                                             13524   2945    78%

After executing `pytest --cov` the above report was generated. @Demirrr you probably would like to see this.
