### ISSUE TITLE
Restore Enrich ontology with axioms feature

### ISSUE THREAD

**Issue by SimonBin** [dice-group/Ontolearn#168]

**Comment by SimonBin** [comment]
hi @Demirrr 

can you check if the following code fulfils the requirement, or otherwise clarify this issue?

```python3
from ontolearn import KnowledgeBase
from owlapy.model import OWLEquivalentClassesAxiom, OWLClass, IRI, OWLObjectIntersectionOf, OWLObjectUnionOf, \
    OWLObjectSomeValuesFrom, OWLObjectInverseOf, OWLObjectProperty, OWLThing

kb = KnowledgeBase(path='../KGs/Carcinogenesis/carcinogenesis.owl')
NS = "http://dl-learner.org/carcinogenesis#"

manager = kb.ontology().get_owl_ontology_manager()
# name of new class
cls_a: OWLClass = OWLClass(IRI.create(NS, "MyEnrichedClass"))

# example concept
concept_a = OWLObjectIntersectionOf(
    (OWLObjectUnionOf((OWLClass(IRI(NS, 'Lead')), OWLClass(IRI(NS, 'Selenium')))),
     OWLObjectSomeValuesFrom(
         property=OWLObjectInverseOf(OWLObjectProperty(IRI(NS, 'hasAtom'))),
         filler=OWLThing)))

equivalent_classes_axiom = OWLEquivalentClassesAxiom(cls_a, concept_a)
manager.add_axiom(kb.ontology(), equivalent_classes_axiom)

# save as new rdfxml file
manager.save_ontology(kb.ontology(), IRI.create("file:/", "new_onto.owl"))

```

**Comment by Demirrr** [comment]
I will take a look at it as soon as possible (at latest the mid of next week). At the first glance, it seems to me what we need it to enrich the ontology.

**Comment by Demirrr** [comment]
The above example is working! It does more than desired. 
The original carcinogenesis.owl file is 10.05MB. After executing the above written script, the generated file (new_onto.owl) is 5.16MB.

This issue is observed in the family dataset as well. The original family dataset is 172.7 kb, wherhase the enriched version 85.3 kb.


```
from ontolearn import KnowledgeBase
from owlapy.model import OWLEquivalentClassesAxiom, OWLClass, IRI, OWLObjectIntersectionOf, OWLObjectUnionOf, \
    OWLObjectSomeValuesFrom, OWLObjectInverseOf, OWLObjectProperty, OWLThing

kb = KnowledgeBase(path='KGs/Family/family-benchmark_rich_background.owl')
NS = "http://www.benchmark.org/family#"

manager = kb.ontology().get_owl_ontology_manager()
# name of new class
cls_a: OWLClass = OWLClass(IRI.create(NS, "MyEnrichedClass"))

# example concept
concept_a = OWLObjectIntersectionOf((OWLClass(IRI(NS, 'Brother')), OWLClass(IRI(NS, 'Father'))))

equivalent_classes_axiom = OWLEquivalentClassesAxiom(cls_a, concept_a)
manager.add_axiom(kb.ontology(), equivalent_classes_axiom)

# save as new rdfxml file
manager.save_ontology(kb.ontology(), IRI.create("file:/", "KGs/Family/demir_family_new_onto.owl"))
```

**Comment by Demirrr** [comment]
# How can we get instances from this newly created class ?

```python
def ClosedWorld_ReasonerFactory(onto: OWLOntology) -> OWLReasoner:
    assert isinstance(onto, OWLOntology_Owlready2)
    base_reasoner = OWLReasoner_Owlready2_TempClasses(ontology=onto)
    reasoner = OWLReasoner_FastInstanceChecker(ontology=onto,
                                               base_reasoner=base_reasoner,
                                               negation_default=True)
    return reasoner

kb = KnowledgeBase(path=args.path_knowledge_base,reasoner_factory=ClosedWorld_ReasonerFactory)

....
# Is this function kb.reasoner().instances() is the retrieval function in CWA ?
print(list(kb.reasoner().instances(equivalent_classes_axiom)))

**Comment by Jean-KOUAGOU** [comment]
The reduction of the size probably has to do with the OWL version, perhaps it is saving the new ontologies as OWL-DL files whilst former files were formatted in OWL-DL2. To verify this, I we may want to load the new files and re-save them using Protégé.

**Comment by SimonBin** [comment]
The original files are written with Protégé or OWL-API, but if we save them using owlapy+owlready2 (same as using owlready2 directly), they will be saved by owlready2.

Just take one thing that happens which will drastically reduce file size, as an example:

- Owlready2 will remove the full IRIs, so instead of http://www.benchmark.org/family#hasChild, owlready2 would only save #hasChild

But if there aren't any bugs in owlready2, then the semantic information content should be the same. So while the files look totally different and their size differs, their meaning should remain the same.

**Comment by Demirrr** [comment]
Thank you for the quick response @Jean-KOUAGOU and @SimonBin .

The issue of restoring enriched ontology is solved :partying_face: :clap:

**Comment by Demirrr** [comment]
Is it possible to add axioms of inclusion ? I havent managed to create an axiom indicating that A is a subclass of B.
