### ISSUE TITLE
Installation steps are instable; TOX fails

### ISSUE THREAD

**Issue by Demirrr** [dice-group/Ontolearn#171]
After following these steps, 
```
git clone https://github.com/dice-group/Ontolearn.git
cd Ontolearn
conda create --name temp python=3.8
conda activate temp
conda env update --name temp
python -c 'from setuptools import setup; setup()' develop
python -c "import ontolearn"
tox  # to test
```
**FileNotFoundError: [Errno 2] No such file or directory: 'KGs/Mutagenesis/mutagenesis.owl'**
is raised due to the following tests.
```
    def test_cardinality_restrictions(self):
        NS = "http://dl-learner.org/mutagen
[error_log.zip](https://github.com/dice-group/Ontolearn/files/7495822/error_log.zip)
esis#"
        ...
    def test_data_properties(self):
        NS = "http://dl-learner.org/mutagenesis#"
        ...
```
Please follow [Naming convension](https://www.python.org/dev/peps/pep-0008/#naming-conventions) of PEP 8 at writing tests.

**Comment by Demirrr** [comment]
[error_log.zip](https://github.com/dice-group/Ontolearn/files/7495823/error_log.zip)

**Comment by SimonBin** [comment]
Thanks for the report!

**Comment by Demirrr** [comment]
A workaround would be adding `./big_gitext/download_big.sh -A` before `tox` (already tested)
