### ISSUE TITLE
port ignoring of complex expression feature from OntoPy 0.0.2

### ISSUE THREAD

**Issue by SimonBin** [dice-group/Ontolearn#196]
the refinement operator might ignore complex expressions

**Comment by Demirrr** [comment]
Thank you!

To give a clear content, if a user has some prior knowledge about the learning problem at hand, we would like to enable the user to inject this prior knowledge into the learning processs. Although this injection inherently have the potential of hurting us in terms of the completeness, user should be able to dedice it for the sake of the computationally efficiency. 

Consider a scenario where all positive examples are FEMALE and negative examples are MALE or (FEMALE AND \forall.HaveDegree.ComputerScience). A user may want to ignore MALE as well as all concepts X \sqsubseteq MALE and their complex expressions with \sqcap (e.g. SON \sqcap etc. from the search. Ignoring implies that we do not invoke a DL reasaner to obtain instances of these concepts. This would most likely to increase our efficiency.

**Comment by SimonBin** [comment]
nb. ignoring atomic classes and roles is already supported on a knowledge base level, then these concepts also will not be part of any refinement
