### ISSUE TITLE
Using a predicted class expression

### ISSUE THREAD

**Issue by Demirrr** [dice-group/Ontolearn#213]
## Standard Class Expression Learning (CEL) Workflow
 
Let (E^+ , E^-) and K =(T,A) be given. Let M denotes a CEL algorithm.

1. M(E^+,E^-,K) =: [C_i, C_j, C_k] generates a sequence class expressions in descending order of their qualities (say F1score).
2. We report C_i.

The above description roughly summarizes the CEL workflow. We would like to go one step ahead and "deploy C_i". 

## Deploying A Learned Class Expression C_i
1. We can serialize/deserialize C_i 
2. We have a new set of assertions describing a person: {Person(**Demir**), Lives(**Demir**,**Hövelhof**)}

We would like to make a prediction on the new individual **Demir**, i.e,. C_i(**Demir**) =1  or C_i(**Demir**)?

### Questions
How can we deploy C_i to classifiy a new instance ?

1. Add these new facts into existing knowledge base, deserialize C_i and check whether **Demir** in RetrievalFunc(C_i) 
2. Do not add these facts into existing knowledge but find another way, e.g., F(C_i,  {Person(**Demir**), Lives(**Demir**,**Hövelhof**), K) => 0 or 1.

**Comment by SimonBin** [comment]
for 1) you will want to fix/implement #175 

if the assertions are in the KB you can also ask hermit/pellet to classify it with
```py
reasoner._sync_reasoner(BaseReasoner_Owlready2.PELLET)
```

it would probably be good to implement (add code to owlapy + mapping for owlready2) `add_axiom` also for `ClassAssertion` and `ObjectPropertyAssertion` so that you can interactively extend a KB with ABox information

**Comment by SimonBin** [comment]
2. can be considered as TBox of original ontology + enriched concept C_i + ABox fragment required to answer the query + individual(s) in question. You could use a new ontology and implement the required parts ((a) implement `tbox_axioms` for OWLOntology (is this possible with owlready2??), (b) implement loading of tbox axioms, ideally through `add_axioms`, (c) implement adding of abox axioms, (d/e) use owlready2's sync_reasoner and/or implementation of #175 to answer the query)
