### ISSUE TITLE
Make PyTorch dependency optional?

### ISSUE THREAD

**Issue by heindorf** [dice-group/Ontolearn#221]
```
import ontolearn
```

gives
```
ModuleNotFoundError: No module named 'torch'
```

although PyTorch is not necessary for many algorithms.

Since PyTorch is a heavy dependency (large file size, not easy to get running on all systems, ...) and not necessary for many algorithms (CELOE, EvoLearner, ...), it should be made optional.

**Comment by heindorf** [comment]
It is possible: https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies

**Comment by Demirrr** [comment]
Great!! Feel free to update the setup file and make a pull request!

**Comment by alkidbaci** [comment]
Speaking up-to-date, `torch` is being used for NCES and DRILL so we have to include it in the default dependencies.
For the moment the optional dependencies are: `httpx`, `pytest`, `gradio`, `ontosample` . 
Therefore I am closing this issue.
