### ISSUE TITLE
Cannot compute instances of OWLThing and OWLNothing

### ISSUE THREAD

**Issue by Jean-KOUAGOU** [dice-group/Ontolearn#237]
Example:
`
Ontolearn/owlapy/fast_instance_checker.py in _find_instances(self, ce)
    346     @singledispatchmethod
    347     def _find_instances(self, ce: OWLClassExpression) -> FrozenSet[OWLNamedIndividual]:
--> 348         raise NotImplementedError(ce)
    349 
    350     @_find_instances.register

NotImplementedError: IRI('http://www.w3.org/2002/07/owl#','Thing')
`
In the example above, the error occurs when querying for the instances of OWLThing

**Comment by LukasBluebaum** [comment]
Fixed by #238
