### ISSUE TITLE
Possible bug in DLSyntaxParser

### ISSUE THREAD

**Issue by nkaralis** [dice-group/Ontolearn#239]
I am using Ontolearn to convert ALC class expressions to SPARQL queries. While trying to convert the class expression `Carbon-194 ⊔ (∃ inBond.⊤)`, the [converter](https://github.com/dice-group/Ontolearn/blob/d29321fd01603cbe7fd88c54461949cb7e93093b/owlapy/owl2sparql/converter.py#L186)  raised a NonImplementedError. It seems that the DLSyntaxParser does not return an OWLClass instance when processing the  [top and bottom concepts](https://github.com/dice-group/Ontolearn/blob/d29321fd01603cbe7fd88c54461949cb7e93093b/owlapy/parser.py#L722), which causes the converter to raise the error. Creating OWLClass instances from the IRIs, solved the issue. However, I am not sure whether this change affects other parts of the library.

Probably related to: #237 and #238

**Comment by LukasBluebaum** [comment]
Fixed by #238
