### ISSUE TITLE
Object Complement Of not implemented at OWLObjectComplementOf(OWLClass(IRI('http://dl-learner.org/ont/','AgeClass3'))) in hepatitis.owl

### ISSUE THREAD

**Issue by Jean-KOUAGOU** [dice-group/Ontolearn#240]
Ontolearn cannot compute the complement of some atomic classes. The header shows an example on the hepatitis ontology. I encountered the same issue on carcinogenesis, mutagenesis, semantic bible, vicodi, family benchmark, ...

To encounter this, just try generating class expressions using a refinement operator.

**Comment by LukasBluebaum** [comment]
The `negation_default` argument in the [FastInstanceChecker](https://github.com/dice-group/Ontolearn/blob/3b033ca94918b2aa6a0a4da94a195cf43e329a44/owlapy/fast_instance_checker.py#L56) has to be set to `True`. I don't really know why that is not the default, unless I'm missing something we should probably change it to `True` per default.
