### ISSUE TITLE
Issue running example file concept_learning_with_ocel.py

### ISSUE THREAD

**Issue by MSAYAK** [dice-group/Ontolearn#261]
Facing this error when running the original code file : "concept_learning_with_ocel.py"

File "concept_learning_with_ocel.py", line 58, in <module>
    model.set_max_runtime(600)
AttributeError: 'OCEL' object has no attribute 'set_max_runtime'

Solution: The code run properly when it is updated as follows:
 
model = OCEL(knowledge_base=target_kb,max_runtime=600,
max_num_of_concepts_tested=10_000_000_000,
iter_bound=10_000_000_000)
model.set_max_runtime(600)

Seems like the "max_runtime" parameter is no longer used. Can you please confirm ? I was able to run the code after removing the parameter.

**Comment by Demirrr** [comment]
Thank you !

**Comment by Demirrr** [comment]
@MSAYAK  [This example](https://github.com/dice-group/Ontolearn/blob/develop/examples/concept_learning_with_ocel.py) seems to run without an issue. Also see https://github.com/dice-group/Ontolearn/pull/260#issuecomment-1547634999 .
