### ISSUE TITLE
Refactoring Interface

### ISSUE THREAD

**Issue by Demirrr** [dice-group/Ontolearn#263]
We should be able to plug and play with our reasoners and learners. 
Ideally, we should have the following setting

```python
answer1= ModelAdapter(learner=CELOE(...),
                     reasoner=ClosedWorldReasoner(..),
                     path="KGs/father.owl").fit(pos={...}, neg={...})
                     
answer2= ModelAdapter(learner=CELOE(...,
                     reasoner=HermiT(..),
                     path="KGs/father.owl").fit(pos={...}, neg={...}) 

answer3= ModelAdapter(learner=CELOE(...,
                     reasoner=SPARQL(url=..)).fit(pos={...}, neg={...}) 
```

By this, we can easily compare the results generated by using different configuration settings. 

Note that if `path==None`, than an instance of a reasoner class requires a URL.

**Comment by Demirrr** [comment]
Each reasoner class should implement some methods including the following ones
```python
class ClosedWorldReasoner:
    def get_instances(self,C:Concept)->set:
        pass

    def get_subclasses(self,C:Concept)->set:
        pass

    def get_equivalent_classes(self,C:Concept)->set:
        pass
```
Ideally, we also explicitly state the type of objects in the returned set.

**Comment by alkidbaci** [comment]
Just for the record: It was decided to create a class `Trainer` in addition to `ModelAdaptor` for the purpose of disentangling the learner initialization from its training. 

@Demirrr please check if the [Trainer class](https://github.com/dice-group/Ontolearn/blob/a534a225c68fb88147a8bd71b02cd15c6b109af6/ontolearn/model_adapter.py#L225C7-L225C14) fulfills your requirements so we can close this issue.
