### ISSUE TITLE
Seperating Owlapy  from Ontolearn

### ISSUE THREAD

**Issue by Demirrr** [dice-group/Ontolearn#285]
Seperating owlapy from ontolearn would help to modularized ontolearn. 
Currently, @SimonBin is the the maintainer of https://pypi.org/project/owlapy/. Ideally, I will be the maintainer of owlapy
1. Create a github repo under dice-group
2. Make a new release of owlapy that [fixes the SPARQL mapping issue](https://github.com/dice-group/Ontolearn/issues/284)
3. Refractor the ontolearn code, where classes from owlapy imported.

**Comment by Demirrr** [comment]
After discussion with @nkaralis, for the time being, removing

1. Superprob
2. Sortedcontainers-stubs from our repo
3. Moving owlapy under ontolearn

If you (@alkidbaci ) have time, could you take care of this issue ?

**Comment by alkidbaci** [comment]
Ok, ill take care of this

**Comment by alkidbaci** [comment]
Should we consider this closed? @Demirrr

**Comment by Demirrr** [comment]
Yes indeed!
