### ISSUE TITLE
Using hypothesis as a binary classifier

### ISSUE THREAD

**Issue by Demirrr** [dice-group/Ontolearn#291]
# Question Description

For a given learning problem, we can return the quality of found best hypothesis/DL concept  as such
```python
for desc in model.best_hypotheses(1):
    print('The result:', renderer.render(desc.concept), 'has quality', desc.quality)
```

We should use a learned DL concept as a binary classifier of an individual.
Ideally, this DL concept maps  
1. an individual existing in the input KB or 
2. a set of triples and an individual not existing in the input KB
into a binary value.

**Comment by alkidbaci** [comment]
I think we already have that functionality in Ontolearn. The `predict` method (check it [here](https://github.com/dice-group/Ontolearn/blob/82da0e07f3d8eaa266dd546fdaebb104cf030e29/ontolearn/base_concept_learner.py#L236C11-L236C12)) provides a binary classification for some given instances and returns a data frame with ones and zeros.

**Comment by Demirrr** [comment]
Could you please add a test for this ?

**Comment by alkidbaci** [comment]
I just noticed that we also have some test cases for this. They are located in the script: `tests/test_base_concept_learner.py`

**Comment by Demirrr** [comment]
That is great!
