### ISSUE TITLE
Including CLIP and NCES into benchmarking

### ISSUE THREAD

**Issue by Demirrr** [dice-group/Ontolearn#302]
Could you @Jean-KOUAGOU add CLIP and NCES into `examples/concept_learning_evaluation.py` ?

Perhaps, you could also modify the script by adressing the following points
1. Modify the current script by introducing [argparse](https://docs.python.org/3/library/argparse.html) that allows us to add the path of embedding files ?
2. Runtime can be given as an input param.

Please let me know if something is unclear

**Comment by Jean-KOUAGOU** [comment]
I cannot find the benchmarking script you are referring to. Can you please
send a link to it?
I only know about deploy_cl.py

**Comment by Demirrr** [comment]
https://github.com/dice-group/Ontolearn/blob/master/examples/concept_learning_evaluation.py

**Comment by Demirrr** [comment]
Please create a branch from develop :)

**Comment by Jean-KOUAGOU** [comment]
Sure. However, I have some comments:

1- NCES won't accept a modified knowledge base as it was trained on a
predefined vocabulary using the full ontology

2- The time argument might be provided, but won't be taken into account.
NCES very fast:). You will input something like 5 seconds, NCES will
compute the solution in 0.1 seconds.:)

3- NCES won't accept the path of embeddings as it needs it own embeddings
and knows where to find them.

Of course I can add argparse for other algorithms. CLIP will need some time
to be integrated into Ontolearn. But it should be possible.

**Comment by Demirrr** [comment]
1. Maybe you could use if else to use a modified knowledge base when NCES is being used to predict a DL concept.

2. Yes you are right :) . 

3. Hmm. [This script](https://github.com/dice-group/Ontolearn/blob/master/examples/advanced-usage-NCES.ipynb) shows that NCES requires the path of embeddings. Is this not valid any more ? Could you please modify examples/concept_learning_evaluation.py in such a manner that we can train NCES and evaluate its performance as we evaluate the performance of other models.
 
4. Please ensure to select "good default arguments" in the argparse for NCES. You can very well ignore the CLIP for the time being if its integration takes considerably more time than the integration of NCES. This script will be used

**Comment by Jean-KOUAGOU** [comment]
3. Could you please modify examples/concept_learning_evaluation.py in such
a manner that we can train NCES and evaluate its performance as we evaluate
the performance of other models.

Would you like to generate training data for NCES, then train it on a given
knowledge base?

**Comment by Demirrr** [comment]
With https://github.com/dice-group/Ontolearn/pull/332, we have the first version of benchmarking results

**Comment by Demirrr** [comment]
Thanks to @Jean-KOUAGOU, we included NCES into ontolearn. NCES can be trained and evaluated see #344
