### ISSUE TITLE
Add expressiveness of CEL algorithms to docs

### ISSUE THREAD

**Issue by bigerl** [dice-group/Ontolearn#306]
It would be good to have the expressiveness of each CEL algrithms, like ALC, SHIQ(D) ... , added to the documentation. 

That would be important for knowing what concepts one can expect from them and also for comparing them. E.g., I would expect that there is trade in the triangle expressiveness, runtime and result quality.

**Comment by Demirrr** [comment]
For the sake of correctness, a search based CEL algorithm (e.g. CELOE, OCEL, DRILL) can operate in ALC as well as SHIQ(D). 
This is depends on the refinement operator and  the input knowledge base.

Ideally, we should have a `class RefinementOperator(dl="ALC")` that returns an refinement operator object operating on **the specified dl solely**. What do you think @alkidbaci ?
