### ISSUE TITLE
NCES not working

### ISSUE THREAD

**Issue by alkidbaci** [dice-group/Ontolearn#322]
There was a bug introduced by the recent changes made by Demir but even when fixing that ( commit 8fe777b367d8efaae3c1cca08fe21532bcdb6448) there are still errors when trying to run NCES. I believe you understand it better @Jean-KOUAGOU, so could you please take a look on it. 

These errors could also be because of the recent changes so I highly think we need to create some test cases for NCES so these kind of  things don't happen again in the future. I can do that but since you know the ins and outs of NCES better than me, it would be best that you do that.

To reproduce the error:
1. checkout [general_adjustments](https://github.com/dice-group/Ontolearn/tree/general_adjustments) branch.
2. execute the command: 
```shell
python main.py --model nces --knowledge_base_path NCESData/family/family.owl
``` 
This goes without saying but make sure you have downloaded NCESData.

**Comment by Demirrr** [comment]
> There was a bug introduced by the recent changes made by Demir but even when fixing that ( commit https://github.com/dice-group/Ontolearn/commit/8fe777b367d8efaae3c1cca08fe21532bcdb6448) there are still errors when trying to run NCES.

Could you please eleborate on the relationship between this commit and NCES ?

**Comment by Demirrr** [comment]
Very good catch! `assertion_path_isfile()` should not be returning None if a valid path is passed

**Comment by Demirrr** [comment]
```
Traceback (most recent call last):
  File "main.py", line 109, in <module>
    execute(get_default_arguments())
  File "/home/nkouagou/Documents/Ontolearn/ontolearn/model_adapter.py", line 392, in execute
    report = "Prediction: " + DLSyntaxObjectRenderer().render(hypothesis) + "Quality: " + \
TypeError: can only concatenate str (not "float") to str
```

It is not related to a package version. The TypeError indicates that one of the items intended to form report is float

**Comment by alkidbaci** [comment]
I was earlier in the office and happen to meet Jean at the moment he was dealing with this. The error shown to Jean is a different one. In my case the error is related with NCES and not the results printing. We concluded that it must be caused by some package version because I have been install all kinds of libraries and probably the version of a package is overwritten. But that's just an assumption, I will have a better look on this.

**Comment by alkidbaci** [comment]
So just for the record, after trying it, the script works perfectly fine on Linux which means the issue is related with the operating system. That make sense because the package that throws the error is `multiprocessing` which works differently depending on the OS. I'm using Windows 11 currently, on which I'm getting the error.

**Comment by Demirrr** [comment]
I guess we can close this issue. What do you think @Jean-KOUAGOU ?

**Comment by Jean-KOUAGOU** [comment]
Yes we can close it

**Comment by Jean-KOUAGOU** [comment]
Please close this issue
