### ISSUE TITLE
TypeError: Can't instantiate abstract class OWLReasoner_FastInstanceChecker with abstract methods super_data_properties, super_object_properties

### ISSUE THREAD

**Issue by renespeck** [dice-group/Ontolearn#346]
Hi, 
I have Ontolearn 0.6.1 installed via pip in conda. I cloned this repo and checked out tag 0.6.1.

When I try the examples, e.g.,  `examples/concept_learning_with_ocel.py`

I get the following error:

```
Traceback (most recent call last):
  File "/store/Github/ontolearn/examples/concept_learning_with_ocel.py", line 20, in <module>
    kb = KnowledgeBase(path=settings['data_path'])
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/store/miniconda3/envs/project/lib/python3.11/site-packages/ontolearn/knowledge_base.py", line 182, in __init__
    self._reasoner = _Default_ReasonerFactory(self._ontology, triplestore_address)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/store/miniconda3/envs/project/lib/python3.11/site-packages/ontolearn/knowledge_base.py", line 39, in _Default_ReasonerFactory
    return OWLReasoner_FastInstanceChecker(ontology=onto, base_reasoner=base_reasoner)

```

Any ideas what I'm doing wrong? Thanks.

**Comment by alkidbaci** [comment]
Hi,

Yes we are aware of this. We made a new release in owlapy where we added two new abstract methods for the base class of OWLReasoner_FastInstanceChecker. This is already taken care of in the develop branch and a new release of Ontolearn will be made very soon. For the time being please uninstall owlapy 0.1.1 and install owlapy==0.1.0. 

Sorry for the inconvenience.

**Comment by sshivam95** [comment]
I am still facing the same issue again with the latest version of ontolearn and owlapy. It works perfectly fine with owlapy==0.1.0

**Comment by alkidbaci** [comment]
I have already tested this scenario. I'm not sure what's going on in your case but can you try to install it in a new environment, check that all the versions are up to date (ontolearn 0.7.0, owlapy 0.1.1) and let me know if this still occurs.

**Comment by sshivam95** [comment]
Thanks for the advice. Works perfectly fine in a new environment.
