### ISSUE TITLE
Restrictions over Nominals

### ISSUE THREAD

**Issue by Demirrr** [dice-group/Ontolearn#355]
Should we we support for the following concepts ?

1. ∃ hasChild.{markus} (owlpy [OWLObjectHasValue](https://ontolearn-docs-dice-group.netlify.app/autoapi/owlapy/model/index.html#owlapy.model.OWLObjectHasValue))
2. ∀ hasChild.{markus}
3. ≥ 1 hasChild.{markus}

If yes, can we also create a SPARQL mapping? @bigerl @alkidbaci ?

**Comment by alkidbaci** [comment]
So I'm providing the code first and then the explanation for it based on owl 2 specification.

```python
from owlapy.model import OWLObjectProperty, IRI, OWLObjectMinCardinality, OWLObjectAllValuesFrom, OWLObjectOneOf, \
    OWLObjectHasValue, OWLObjectSomeValuesFrom, OWLNamedIndividual

hasChild = OWLObjectProperty(IRI('http://example.com/father#','hasChild'))
markus = OWLNamedIndividual(IRI('http://example.com/father#','markus'))

# 1. ∃ hasChild.{markus}
existHasChildMarkus = OWLObjectSomeValuesFrom(property=hasChild, filler=OWLObjectOneOf(markus))
# or
existHasChildMarkus = OWLObjectHasValue(property=hasChild, individual=markus).as_some_values_from()

# 2. ∀ hasChild.{markus}
forAllHasChildMarkus = OWLObjectAllValuesFrom(property=hasChild, filler=OWLObjectOneOf(markus))

# 3. ≥ 1 hasChild.{markus}
atLeastOneHasChildMarkus = OWLObjectMinCardinality(cardinality=1, property=hasChild, filler=OWLObjectOneOf(markus))

```
The following description is from [OWL 2 Specifications](https://www.w3.org/):

OWLObjectHasValue is defined as "Self-Restriction"
> A self-restriction ObjectHasSelf( OPE ) consists of an object property expression OPE, and it contains all those individuals that 
   are connected by OPE to themselves.

OWLObjectSomeValuesFrom is defined as "Existential Quantification" (1)
> An existential class expression ObjectSomeValuesFrom( OPE CE ) consists of an object property expression OPE and a class expression CE, and it contains all those individuals that are connected by OPE to an individual that is an instance of CE. Provided that OPE is simple according to the definition in [Section 11](https://www.w3.org/TR/owl2-syntax/#Global_Restrictions_on_Axioms_in_OWL_2_DL), such a class expression can be seen as a syntactic shortcut for the class expression ObjectMinCardinality( 1 OPE CE ).

OWLObjectOneOf is defined as "Enumeration of Individuals" (it can consist only of a single individual)
> An enumeration of individuals ObjectOneOf( a1 ... an ) contains exactly the individuals ai with 1 ≤ i ≤ n.

OWLObjectAllValuesFrom is defined as "Universal Quantifier" (2)
> A universal class expression ObjectAllValuesFrom( OPE CE ) consists of an object property expression OPE and a class expression CE, and it contains all those individuals that are connected by OPE only to individuals that are instances of CE. Provided that OPE is simple according to the definition in [Section 11](https://www.w3.org/TR/owl2-syntax/#Global_Restrictions_on_Axioms_in_OWL_2_DL), such a class expression can be seen as a syntactic shortcut for the class expression ObjectMaxCardinality( 0 OPE ObjectComplementOf( CE ) ).

OWLObjectMinCardinality is defined as "Minimum Cardinality" (3)
>A minimum cardinality expression ObjectMinCardinality( n OPE CE ) consists of a nonnegative integer n, an object property expression OPE, and a class expression CE, and it contains all those individuals that are connected by OPE to at least n different individuals that are instances of CE. If CE is missing, it is taken to be owl:Thing.

------------------------------------------------------------

As for the SPARQL mapping we can use [owl2sparql converter](https://github.com/dice-group/owlapy/blob/main/owlapy/owl2sparql/converter.py). It has support for all the above mentioned classes (`OWLObjectSomeValuesFrom`, `OWLObjectAllValuesFrom`, `OWLObjectMinCardinality`).

Here is the code and the output:
```python
from owlapy.owl2sparql.converter import Owl2SparqlConverter
converter = Owl2SparqlConverter()

print(converter.convert("?var", existHasChildMarkus))
# ['?var <http://example.com/father#hasChild> ?s_1 . ', ' FILTER ( ?s_1 IN ( ', '<http://example.com/father#markus>', ' )']

print(converter.convert("?var", forAllHasChildMarkus))

 # ['{', '?var <http://example.com/father#hasChild> ?s_1 . ', '{ SELECT ?var ( COUNT( DISTINCT ?s_2 ) AS ?cnt_1 ) WHERE { ', '?var <http://example.com/father#hasChild> ?s_2 . ', ' FILTER ( ?s_2 IN ( ', '<http://example.com/father#markus>', ' )', ' } GROUP BY ?var }', '{ SELECT ?var ( COUNT( DISTINCT ?s_3 ) AS ?cnt_2 ) WHERE { ', '?var <http://example.com/father#hasChild> ?s_3 . ', ' } GROUP BY ?var }', ' FILTER( ?cnt_1 = ?cnt_2 )', '} UNION { ', '?var ?s_4 ?s_5 . ', 'FILTER NOT EXISTS { ', '?var <http://example.com/father#hasChild> ?s_6 . ', ' } }']

print(converter.convert("?var", atLeastOneHasChildMarkus ))
# ['{ SELECT ?var WHERE { ', '?var <http://example.com/father#hasChild> ?s_1 . ', ' FILTER ( ?s_1 IN ( ', '<http://example.com/father#markus>', ' )', ' } GROUP BY ?var HAVING ( COUNT ( ?s_1 ) >= 1 ) }']

```

**Comment by Demirrr** [comment]
From my perspective, the SPARQL query mappings of concepts are correct. Could you please confirm @ngonga @bigerl @nkaralis ?

**Comment by Demirrr** [comment]
Closing this issue as the SPARQL mappings are correct
