### ISSUE TITLE
owlapy version restriction

### ISSUE THREAD

**Issue by alkidbaci** [dice-group/Ontolearn#372]
I suggest that we set the owlapy version in `setup.py` to strict equal ( == ) instead of equal or greater ( >=) to avoid future issues like #346 . 

The idea is that during development in ontolearn we use the latest owlapy version and at the moment of a new release this should be the exact version set as requirement. This ensures that whatever changes we make to owlapy after ontolearn release, it wont cause any issue because we are using strict equal and we know that any change introduced by a new release of owlapy wont cause any issue to the current release of Ontolearn. 

Possible other solutions: 
1. We can leave the required version of owlapy as it is, but at the moment we plan a new release of owlapy we should adapt ontolearn to any possible change that may introduce a bug and make a new release for ontolearn as well. This is not the best solution because during the time frame of the 2 releases, users that install ontolearn will install the new version of owlapy but not the updated version of ontolearn. 
2. We can combine ">=" and "<" operators to restrict the version of owlapy to just small incrementations that indicate for bug fixing or similar small stuff and whenever a significant update happens which may need alterations of ontolearn then the latest valid version will be used. 
For example we set the requirement version to `owlapy >=0.1.2,<1.0.0. In case we make a new release 0.1.4 of owlapy where we fixed a bug then that wont interfere with the current state of ontolearn. But if we release owlapy 1.0.0 where we perform some heavy refactoring that will totally set ontolearn imports on chaos :D then this version will not be installed but the lates valid one will be used instead.

**Comment by Demirrr** [comment]
Fair point!
