### ISSUE TITLE
Replace `≥1` with `≥2`

### ISSUE THREAD

**Issue by MichaelRoeder** [dice-group/Ontolearn#404]
# User story

From the point of view of a user (that may have a limited understanding of DL :sweat_smile: ), a lot of statements that are checked seem to be redundant, e.g., `∃ p.⊤` and `≥1 p.⊤` seem to be equivalent.

# Suggestion

Only make use of `∃ p.⊤`. If `≥n p.⊤` is necessary to be able to further refine this, e.g., with respect to a more restrictive `n` I would suggest to directly start with `≥2 p.⊤`.

**Comment by Demirrr** [comment]
Yes `∃ p.⊤` and `≥1 p.⊤` see https://www.w3.org/TR/owl2-syntax/#Existential_Quantification.

Sure we can set the default parameter of `n` in the cardinality restrictions `≥ n p.⊤` to be 1 in LengthBasedRefinement

**Comment by Demirrr** [comment]
Fixed in https://github.com/dice-group/Ontolearn/pull/406 .
