### ISSUE TITLE
Owlapy 1.3.2 import incompability 

### ISSUE THREAD

**Issue by LckyLke** [dice-group/Ontolearn#471]
https://github.com/dice-group/Ontolearn/blob/169810f4efb1a67c8ec8d06e54385c80155c1b82/ontolearn/knowledge_base.py#L45

this import for OntologyReasoner does not exist any more when manually upgrading to owlapy 1.3.2. 

I presume there are similar import errors elsewhere

**Comment by Demirrr** [comment]
Do we need to use owlapy 1.3.1 for the time being ?

**Comment by LckyLke** [comment]
so retrieval_eval_under_incomplete cant run properly

**Comment by Demirrr** [comment]
Very good. This issue of parsing restrictions with nominals have been mentioned in https://github.com/dice-group/Ontolearn/issues/472.
