### ISSUE TITLE
Error with retrieval_eval.py

### ISSUE THREAD

**Issue by alkidbaci** [dice-group/Ontolearn#492]
This PR #488 changes makes this example (`retrieval_eval.py`) fail when testing on father ontology. The dataframe [here](https://github.com/dice-group/Ontolearn/blob/77fae24bfeeeda3f0a67749527863089e12aef69/examples/retrieval_eval.py#L245) is empty and the next line throws a key error. Would need your help @LckyLke on what's going on here and whether we can provide a solution for this.  
You can run the `test_retrieval_eval` on `tests/test_retrieval_eval_examples.py` in branch _owlapy-1.3.3_ because thats holding this PR #486 right now.

**Comment by LckyLke** [comment]
I will have a look at it
