### ISSUE TITLE
Compare performance to DL Learner

### ISSUE THREAD

**Issue by heindorf** [dice-group/Ontolearn#56]
Create small test cases / micro benchmarks to compare the performance of OntoPy to DL Learner (both in terms of predictive performance and runtime)

**Comment by LNSieger** [comment]
How is the status with that?

**Comment by LNSieger** [comment]
How is the status with this?

**Comment by Demirrr** [comment]
Previosuly, I have created a DL-Binder that allows us to use DL-learner within our framework. 
Finding and integrating this class into https://github.com/dice-group/Ontolearn/blob/master/examples/concept_learning_evaluation.py would be great!

**Comment by Demirrr** [comment]
With https://github.com/dice-group/Ontolearn/pull/332, we have benchmarking results
