### ISSUE TITLE
How would we handle DataProperties in RAKI use-case data?

### ISSUE THREAD

**Issue by bigerl** [dice-group/Ontolearn#60]
In RAKI we strive to support ALC. If I understand it correctly, OWL DataProperties are not covered by ALC. 

How should we handle data properties present in a dataset?

Options I see:

1. handle it as if it was a unrestricted ObjectProperty
2. ignore it completely
3. fail

**Comment by SimonBin** [comment]
data properties now added by @LukasBluebaum
