### ISSUE TITLE
WIP: Reasoning Support

### ISSUE THREAD

**Issue by heindorf** [dice-group/Ontolearn#65]
For some use cases, our library needs reasoning support.  This seems particularly important for the Siemens use case in RAKI. Also for DAIKIRI it would be beneficial (e.g., transitivity of previous/next events).

Potential options to realize reasoning:
  1.  Use owlready2's reasoner bindings
  2.  Create our own reasoner bindings to a Java reasoner, e.g., to HermiT or Pellet
  3. Use existing Python reasoner, e.g., CWM or OWL-RL (might be slow)

I believe the options should be explored in this order. Feel free to add further comments, opinions, and the results of initial approaches/experiments.

**Comment by SimonBin** [comment]
- Alex' Tentris
- SPARQL
- (OWLLink) we don't currently need open world
