### ISSUE TITLE
Feature: Cardinality restrictions

### ISSUE THREAD

**Issue by Demirrr** [dice-group/Ontolearn#83]
Page 53 in [1]:
1. <img src="https://render.githubusercontent.com/render/math?math=( \geq R)^I = ..."> and 
2. <img src="https://render.githubusercontent.com/render/math?math=( \leq R)^I = ...">

[1]@book{baader2003description,
title={The description logic handbook: Theory, implementation and applications},
author={Baader, Franz and Calvanese, Diego and McGuinness, Deborah and Patel-Schneider, Peter and Nardi, Daniele and others},
year={2003},
publisher={Cambridge university press}
}

**Comment by SimonBin** [comment]
now possible to express in OWL-APy
